"""Feature construction for the forecast-error model (the only LEARNED component).

Inputs (all PUBLIC, none generated by our simulator):
- day-ahead NWP GHI/temperature/cloud for ICON and GFS (Open-Meteo Previous-Runs API, forecast issued the day before;
  falls back to the short-lead Historical Forecast archive if the day-ahead archive is unavailable, and says so),
- clear-sky GHI from pvlib at the site,
- calendar features.
Target: ERA5 reanalysis GHI (primary proxy). NASA POWER GHI is kept as a second, independent proxy for evaluation.
Only daytime rows (clear-sky GHI > 20 W/m2) are used.
"""
from __future__ import annotations

from typing import Dict, List, Tuple

import numpy as np
import pandas as pd

from ..core.config import SunflowConfig
from ..data.cache import cache_file
from ..physics.pv import clearsky_ghi

FEATURES: List[str] = [
    "icon_ghi", "gfs_ghi", "nwp_mean_ghi", "nwp_diff_ghi", "cs_ghi", "icon_kt", "gfs_kt",
    "icon_temp", "icon_cloud", "gfs_cloud", "hour", "doy_sin", "doy_cos",
]
TRAIN_YEARS: Tuple[int, int] = (2023, 2024)
TEST_YEARS: Tuple[int, int] = (2025, 2025)


def _load(name: str) -> pd.DataFrame:
    p = cache_file(name)
    if not p.exists():
        raise FileNotFoundError(f"{p} missing; run scripts/fetch_data.py")
    df = pd.read_csv(p)
    df["time"] = pd.to_datetime(df["time"])
    return df


def nwp_source_names() -> Dict[str, str]:
    """Prefer the day-ahead (previous-day1) archives; fall back to the short-lead archive and label it."""
    out = {}
    for model in ("icon_seamless", "gfs_seamless"):
        day1 = cache_file(f"nwp_day1_{model}_latur")
        out[model] = f"nwp_day1_{model}_latur" if day1.exists() else f"nwp_{model}_latur"
    return out


def build_dataset(cfg: SunflowConfig) -> pd.DataFrame:
    era = _load("era5_hourly_latur")[["time", "ghi", "temp"]].rename(columns={"ghi": "y_era5", "temp": "era5_temp"})
    names = nwp_source_names()
    icon = _load(names["icon_seamless"])[["time", "ghi", "temp", "cloud"]].rename(columns={"ghi": "icon_ghi", "temp": "icon_temp", "cloud": "icon_cloud"})
    gfs = _load(names["gfs_seamless"])[["time", "ghi", "temp", "cloud"]].rename(columns={"ghi": "gfs_ghi", "temp": "gfs_temp", "cloud": "gfs_cloud"})
    df = era.merge(icon, on="time", how="inner").merge(gfs, on="time", how="inner")
    try:
        nasa = _load("nasa_power_hourly_latur")[["time", "ghi"]].rename(columns={"ghi": "y_nasa"})
        df = df.merge(nasa, on="time", how="left")
    except FileNotFoundError:
        df["y_nasa"] = np.nan
    # clear-sky at the hour centre (Open-Meteo hourly radiation is the mean of the preceding hour)
    centred = pd.DatetimeIndex(df["time"]).tz_localize(cfg.site.timezone) - pd.Timedelta(minutes=30)
    df["cs_ghi"] = clearsky_ghi(centred, cfg.site)
    df = df[df["cs_ghi"] > 20.0].copy()
    df["icon_kt"] = (df["icon_ghi"] / df["cs_ghi"]).clip(0, 1.3)
    df["gfs_kt"] = (df["gfs_ghi"] / df["cs_ghi"]).clip(0, 1.3)
    df["nwp_mean_ghi"] = 0.5 * (df["icon_ghi"] + df["gfs_ghi"])
    df["nwp_diff_ghi"] = df["icon_ghi"] - df["gfs_ghi"]
    df["hour"] = df["time"].dt.hour
    doy = df["time"].dt.dayofyear
    df["doy_sin"] = np.sin(2 * np.pi * doy / 365.25)
    df["doy_cos"] = np.cos(2 * np.pi * doy / 365.25)
    df["year"] = df["time"].dt.year
    # persistence baseline: ERA5 same hour, previous day
    prev = era.copy(); prev["time"] = prev["time"] + pd.Timedelta(days=1)
    prev = prev.rename(columns={"y_era5": "persist_ghi"})[["time", "persist_ghi"]]
    df = df.merge(prev, on="time", how="left")
    df["nwp_source"] = names["icon_seamless"]
    return df.dropna(subset=FEATURES + ["y_era5"]).reset_index(drop=True)


def split(df: pd.DataFrame) -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    train = df[(df["year"] >= TRAIN_YEARS[0]) & (df["year"] <= TRAIN_YEARS[1])]
    test = df[(df["year"] >= TEST_YEARS[0]) & (df["year"] <= TEST_YEARS[1])]
    extra = df[df["year"] > TEST_YEARS[1]]
    return train.reset_index(drop=True), test.reset_index(drop=True), extra.reset_index(drop=True)
